<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BrewUp.Purchases.SharedKernel</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Muflone" Version="8.5.0" />
    </ItemGroup>

</Project>
